sudo: required
services:
    — docker
before_install:
    — docker build -t ghislainyankam/react-test -f ./client/Dockerfile.dev ./client
script:
    — docker run -e CI=true ghislainyankam/react-test npm run test — — coverage
after_success:
    — docker build -t ghislainyankam/my-backend ./server
    — docker build -t ghislainyankam/my-frontend ./client
    — echo “$DOCKER_PASSWORD” | docker login -u “$DOCKER_USER” — password-stdin

    — docker tag my-frontend $DOCKER_USER/my-frontend:$TRAVIS_BUILD_NUMBER
    — docker push $DOCKER_USER/my-frontend:$TRAVIS_BUILD_NUMBER
    — docker tag my-frontend $DOCKER_USER/my-frontend:latest
    
    — docker tag my-backend $DOCKER_USER/my-backend:$TRAVIS_BUILD_NUMBER
    — docker push $DOCKER_USER/my-backend:$TRAVIS_BUILD_NUMBER
    — docker tag my-backend $DOCKER_USER/my-backend:latest

deploy:
    provider: elasticbeanstalk
    region: ap-northeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-northeast-1-340135579499
    bucket_path: docker-multi
    on:
        branch: master
