version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./my-back-end
    ports:
      - "4050:4050"
    volumes:
      - ./my-back-app:/app/backend
      - /app/backend/node_modules
  client:
    build:
      dockerfile: Dockerfile
      context: ./my-frond-end
    ports:
      - "5050:5050"
    volumes:
      - ./my-frond-app:/app/frondend
      - /app/frondend/node_modules

  